[2021-12-03T22:18:16.9950175] [2021-12-03T22:18:16.992835] .\save_files\public\Alunity_Compromised_Accounts.json does not exist!
Dec 03, 2021 10:18:19 PM io.alunity.content.boosts.Boosts init
INFO: Loaded 17 boosts.
Dec 03, 2021 10:18:19 PM io.alunity.model.definitions.ItemDef load
INFO: Loaded 14047 item definitions.
Dec 03, 2021 10:18:20 PM io.alunity.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Dec 03, 2021 10:18:20 PM io.alunity.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Dec 03, 2021 10:18:20 PM io.alunity.model.entity.npc.NPCRelationship setup
INFO: Initialized 0 npc relationships.
Dec 03, 2021 10:18:20 PM io.alunity.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Dec 03, 2021 10:18:34 PM io.alunity.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Dec 03, 2021 10:18:34 PM io.alunity.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Dec 03, 2021 10:18:34 PM io.alunity.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 3217 npcs.
Dec 03, 2021 10:18:35 PM io.alunity.content.commands.CommandManager initializeCommands
INFO: Loaded 261 commands.
Dec 03, 2021 10:18:35 PM io.alunity.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Dec 03, 2021 10:18:35 PM io.alunity.content.dailyrewards.DailyRewardsRecords load
INFO: Loaded data on 1 claimed daily rewards.
[2021-12-03T22:18:59.9498581] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T22:18:59.9498581] 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
[2021-12-03T22:18:59.9498581] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
[2021-12-03T22:18:59.9498581] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[2021-12-03T22:18:59.9498581] 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[2021-12-03T22:18:59.9498581] 	at io.alunity.sql.HikariConnectionProvider.<init>(HikariConnectionProvider.java:19)
[2021-12-03T22:18:59.9498581] 	at io.alunity.sql.DatabaseManager.getConnectionProvider(DatabaseManager.java:174)
[2021-12-03T22:18:59.9498581] 	at io.alunity.sql.DatabaseManager.executeImmediate(DatabaseManager.java:141)
[2021-12-03T22:18:59.9498581] 	at io.alunity.sql.DatabaseManager.executeImmediate(DatabaseManager.java:130)
[2021-12-03T22:18:59.9498581] 	at io.alunity.net.login.RS2LoginProtocol.fetchDisplayName(RS2LoginProtocol.java:593)
[2021-12-03T22:18:59.9498581] 	at io.alunity.net.login.RS2LoginProtocol.loadPlayer(RS2LoginProtocol.java:558)
[2021-12-03T22:18:59.9498581] 	at io.alunity.net.login.RS2LoginProtocol.login(RS2LoginProtocol.java:471)
[2021-12-03T22:18:59.9498581] 	at io.alunity.net.login.RS2LoginProtocol.decode(RS2LoginProtocol.java:313)
[2021-12-03T22:18:59.9498581] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[2021-12-03T22:18:59.9498581] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[2021-12-03T22:18:59.9498581] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[2021-12-03T22:18:59.9498581] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[2021-12-03T22:18:59.9498581] 	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:504)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[2021-12-03T22:18:59.9498581] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[2021-12-03T22:18:59.9498581] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[2021-12-03T22:18:59.9498581] 	at java.base/java.lang.Thread.run(Thread.java:832)
[2021-12-03T22:18:59.9498581] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-12-03T22:18:59.965489] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[2021-12-03T22:18:59.965489] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
[2021-12-03T22:18:59.965489] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[2021-12-03T22:18:59.965489] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
[2021-12-03T22:18:59.965489] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
[2021-12-03T22:18:59.965489] 	... 39 more
[2021-12-03T22:18:59.965489] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T22:18:59.965489] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-03T22:18:59.965489] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-03T22:18:59.965489] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-03T22:18:59.965489] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-12-03T22:18:59.965489] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-12-03T22:18:59.965489] 	... 47 more
[2021-12-03T22:18:59.965489] Caused by: java.net.ConnectException: Connection timed out: no further information
[2021-12-03T22:18:59.965489] 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2021-12-03T22:18:59.965489] 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
[2021-12-03T22:18:59.965489] 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
[2021-12-03T22:18:59.965489] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[2021-12-03T22:18:59.965489] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-12-03T22:18:59.965489] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-12-03T22:18:59.965489] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-12-03T22:18:59.965489] 	... 50 more
[2021-12-03T23:44:39.9325072] com.fasterxml.jackson.databind.JsonMappingException: while parsing a block mapping
 in 'reader', line 16, column 3:
      url: "jdbc:mysql://92.204.221.12 ... 
      ^
expected <block end>, but found '<scalar>'
 in 'reader', line 18, column 28:
      password: "e&{51EbB4O.m" //im trust you fully you can go  ... 
                               ^

 at [Source: (File); line: 18, column: 13] (through reference chain: io.alunity.ServerConfiguration["hiscores_database"])
[2021-12-03T23:44:39.9365063] 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
[2021-12-03T23:44:39.9365063] 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
[2021-12-03T23:44:39.9365063] 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
[2021-12-03T23:44:39.9375047] 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
[2021-12-03T23:44:39.9375047] 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[2021-12-03T23:44:39.9375047] 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
[2021-12-03T23:44:39.9375047] 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
[2021-12-03T23:44:39.9375047] 	at io.alunity.util.JsonUtil.fromYaml(JsonUtil.java:124)
[2021-12-03T23:44:39.9375047] 	at io.alunity.Server.loadConfiguration(Server.java:240)
[2021-12-03T23:44:39.9375047] 	at io.alunity.Server.lambda$main$0(Server.java:173)
[2021-12-03T23:44:39.9375047] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:44:39.9375047] Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 16, column 3:
      url: "jdbc:mysql://92.204.221.12 ... 
      ^
expected <block end>, but found '<scalar>'
 in 'reader', line 18, column 28:
      password: "e&{51EbB4O.m" //im trust you fully you can go  ... 
                               ^

 at [Source: (File); line: 18, column: 27]
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:359)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:861)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
[2021-12-03T23:44:39.9385056] 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
[2021-12-03T23:44:39.9385056] 	... 7 more
[2021-12-03T23:44:39.939505] Caused by: while parsing a block mapping
 in 'reader', line 16, column 3:
      url: "jdbc:mysql://92.204.221.12 ... 
      ^
expected <block end>, but found '<scalar>'
 in 'reader', line 18, column 28:
      password: "e&{51EbB4O.m" //im trust you fully you can go  ... 
                               ^

[2021-12-03T23:44:39.939505] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
[2021-12-03T23:44:39.939505] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[2021-12-03T23:44:39.939505] 	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
[2021-12-03T23:44:39.939505] 	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:355)
[2021-12-03T23:44:39.939505] 	... 12 more
[2021-12-03T23:45:11.7668782] java.lang.IllegalArgumentException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI.create(URI.java:906)
[2021-12-03T23:45:11.7709164] 	at io.alunity.sql.DatabaseCredentials.getURI(DatabaseCredentials.java:27)
[2021-12-03T23:45:11.7709164] 	at io.alunity.sql.DatabaseCredentials.getName(DatabaseCredentials.java:31)
[2021-12-03T23:45:11.7709164] 	at io.alunity.Server.loadData(Server.java:134)
[2021-12-03T23:45:11.7709164] 	at io.alunity.Server.lambda$main$0(Server.java:180)
[2021-12-03T23:45:11.7709164] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:45:11.7709164] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI$Parser.fail(URI.java:2938)
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI$Parser.checkChars(URI.java:3109)
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI$Parser.parse(URI.java:3145)
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI.<init>(URI.java:623)
[2021-12-03T23:45:11.7709164] 	at java.base/java.net.URI.create(URI.java:904)
[2021-12-03T23:45:11.7709164] 	... 5 more
[2021-12-03T23:46:45.1755761] java.lang.IllegalArgumentException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:46:45.1786125] 	at java.base/java.net.URI.create(URI.java:906)
[2021-12-03T23:46:45.1786125] 	at io.alunity.sql.DatabaseCredentials.getURI(DatabaseCredentials.java:27)
[2021-12-03T23:46:45.1786125] 	at io.alunity.sql.DatabaseCredentials.getName(DatabaseCredentials.java:31)
[2021-12-03T23:46:45.1786125] 	at io.alunity.Server.loadData(Server.java:134)
[2021-12-03T23:46:45.1786125] 	at io.alunity.Server.lambda$main$0(Server.java:180)
[2021-12-03T23:46:45.1806578] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:46:45.1806578] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:46:45.1806578] 	at java.base/java.net.URI$Parser.fail(URI.java:2938)
[2021-12-03T23:46:45.1806578] 	at java.base/java.net.URI$Parser.checkChars(URI.java:3109)
[2021-12-03T23:46:45.1806578] 	at java.base/java.net.URI$Parser.parse(URI.java:3145)
[2021-12-03T23:46:45.1806578] 	at java.base/java.net.URI.<init>(URI.java:623)
[2021-12-03T23:46:45.1806578] 	at java.base/java.net.URI.create(URI.java:904)
[2021-12-03T23:46:45.1806578] 	... 5 more
[2021-12-03T23:48:27.0766285] java.lang.IllegalArgumentException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:48:27.0806296] 	at java.base/java.net.URI.create(URI.java:906)
[2021-12-03T23:48:27.0806296] 	at io.alunity.sql.DatabaseCredentials.getURI(DatabaseCredentials.java:27)
[2021-12-03T23:48:27.0806296] 	at io.alunity.sql.DatabaseCredentials.getName(DatabaseCredentials.java:31)
[2021-12-03T23:48:27.0806296] 	at io.alunity.Server.loadData(Server.java:134)
[2021-12-03T23:48:27.0806296] 	at io.alunity.Server.lambda$main$0(Server.java:179)
[2021-12-03T23:48:27.0806296] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:48:27.0806296] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 8: derby:C:\Users\Administrator/public_main;create=true
[2021-12-03T23:48:27.0816266] 	at java.base/java.net.URI$Parser.fail(URI.java:2938)
[2021-12-03T23:48:27.0816266] 	at java.base/java.net.URI$Parser.checkChars(URI.java:3109)
[2021-12-03T23:48:27.0816266] 	at java.base/java.net.URI$Parser.parse(URI.java:3145)
[2021-12-03T23:48:27.0826241] 	at java.base/java.net.URI.<init>(URI.java:623)
[2021-12-03T23:48:27.0826241] 	at java.base/java.net.URI.create(URI.java:904)
[2021-12-03T23:48:27.0836279] 	... 5 more
[2021-12-03T23:50:09.6543301] [2021-12-03T23:50:09.6503268] .\save_files\public\Alunity_Compromised_Accounts.json does not exist!
Dec 03, 2021 11:50:10 PM io.alunity.content.boosts.Boosts init
INFO: Loaded 17 boosts.
Dec 03, 2021 11:50:10 PM io.alunity.model.definitions.ItemDef load
INFO: Loaded 14047 item definitions.
Dec 03, 2021 11:50:11 PM io.alunity.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Dec 03, 2021 11:50:11 PM io.alunity.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Dec 03, 2021 11:50:11 PM io.alunity.model.entity.npc.NPCRelationship setup
INFO: Initialized 0 npc relationships.
Dec 03, 2021 11:50:11 PM io.alunity.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Dec 03, 2021 11:50:26 PM io.alunity.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Dec 03, 2021 11:50:26 PM io.alunity.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Dec 03, 2021 11:50:26 PM io.alunity.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 3217 npcs.
Dec 03, 2021 11:50:27 PM io.alunity.content.commands.CommandManager initializeCommands
INFO: Loaded 261 commands.
Dec 03, 2021 11:50:27 PM io.alunity.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Dec 03, 2021 11:50:27 PM io.alunity.content.dailyrewards.DailyRewardsRecords load
INFO: Loaded data on 1 claimed daily rewards.
[2021-12-03T23:51:26.316322] [2021-12-03T23:51:26.3123231] .\save_files\public\Alunity_Compromised_Accounts.json does not exist!
Dec 03, 2021 11:51:27 PM io.alunity.content.boosts.Boosts init
INFO: Loaded 17 boosts.
Dec 03, 2021 11:51:27 PM io.alunity.model.definitions.ItemDef load
INFO: Loaded 14047 item definitions.
Dec 03, 2021 11:51:27 PM io.alunity.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Dec 03, 2021 11:51:27 PM io.alunity.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Dec 03, 2021 11:51:28 PM io.alunity.model.entity.npc.NPCRelationship setup
INFO: Initialized 0 npc relationships.
Dec 03, 2021 11:51:28 PM io.alunity.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Dec 03, 2021 11:51:42 PM io.alunity.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Dec 03, 2021 11:51:42 PM io.alunity.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Dec 03, 2021 11:51:42 PM io.alunity.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 3217 npcs.
Dec 03, 2021 11:51:42 PM io.alunity.content.commands.CommandManager initializeCommands
INFO: Loaded 261 commands.
Dec 03, 2021 11:51:42 PM io.alunity.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Dec 03, 2021 11:51:42 PM io.alunity.content.dailyrewards.DailyRewardsRecords load
INFO: Loaded data on 1 claimed daily rewards.
[2021-12-03T23:57:12.7685096] [2021-12-03T23:57:12.7645895] .\save_files\public\Alunity_Compromised_Accounts.json does not exist!
Dec 03, 2021 11:57:13 PM io.alunity.content.boosts.Boosts init
INFO: Loaded 17 boosts.
Dec 03, 2021 11:57:14 PM io.alunity.model.definitions.ItemDef load
INFO: Loaded 14047 item definitions.
Dec 03, 2021 11:57:14 PM io.alunity.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Dec 03, 2021 11:57:14 PM io.alunity.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Dec 03, 2021 11:57:14 PM io.alunity.model.entity.npc.NPCRelationship setup
INFO: Initialized 0 npc relationships.
Dec 03, 2021 11:57:14 PM io.alunity.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Dec 03, 2021 11:57:29 PM io.alunity.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Dec 03, 2021 11:57:29 PM io.alunity.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Dec 03, 2021 11:57:29 PM io.alunity.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 3217 npcs.
Dec 03, 2021 11:57:30 PM io.alunity.content.commands.CommandManager initializeCommands
INFO: Loaded 261 commands.
Dec 03, 2021 11:57:30 PM io.alunity.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Dec 03, 2021 11:57:30 PM io.alunity.content.dailyrewards.DailyRewardsRecords load
INFO: Loaded data on 1 claimed daily rewards.
[2021-12-03T23:58:00.9009413] org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://92.204.221.12/game_alunity?useSSL=false&serverTimezone=UTC) for user 'Alunity_Game': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

[2021-12-03T23:58:00.9059346] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
[2021-12-03T23:58:00.9059346] 	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
[2021-12-03T23:58:00.9059346] 	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
[2021-12-03T23:58:00.9059346] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
[2021-12-03T23:58:00.9070185] 	at io.alunity.Server.loadData(Server.java:138)
[2021-12-03T23:58:00.9070185] 	at io.alunity.Server.lambda$main$0(Server.java:176)
[2021-12-03T23:58:00.9070185] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:58:00.9070185] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-12-03T23:58:00.9070185] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
[2021-12-03T23:58:00.9070185] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
[2021-12-03T23:58:00.9070185] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
[2021-12-03T23:58:00.9070185] 	... 6 more
[2021-12-03T23:58:00.9070185] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T23:58:00.9070185] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-03T23:58:00.9070185] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-03T23:58:00.9070185] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-03T23:58:00.9070185] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-12-03T23:58:00.9070185] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-12-03T23:58:00.9070185] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-12-03T23:58:00.9105209] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-12-03T23:58:00.9105209] 	... 12 more
[2021-12-03T23:58:00.9105209] Caused by: java.net.ConnectException: Connection timed out: connect
[2021-12-03T23:58:00.9105209] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-12-03T23:58:00.9105209] 	at java.base/sun.nio.ch.Net.connect(Net.java:503)
[2021-12-03T23:58:00.9105209] 	at java.base/sun.nio.ch.Net.connect(Net.java:492)
[2021-12-03T23:58:00.9105209] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-12-03T23:58:00.9115228] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-12-03T23:58:00.9115228] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-12-03T23:58:00.9115228] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-12-03T23:58:00.9115228] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-12-03T23:58:00.9115228] 	... 15 more
[2021-12-03T23:59:01.0285913] org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://92.204.221.12/game_alunity?useSSL=false&serverTimezone=UTC) for user 'Alunity_Game': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

[2021-12-03T23:59:01.0335909] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
[2021-12-03T23:59:01.0335909] 	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
[2021-12-03T23:59:01.0335909] 	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
[2021-12-03T23:59:01.0335909] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
[2021-12-03T23:59:01.0335909] 	at io.alunity.Server.loadData(Server.java:139)
[2021-12-03T23:59:01.0335909] 	at io.alunity.Server.lambda$main$0(Server.java:177)
[2021-12-03T23:59:01.0335909] 	at io.alunity.GameThread.run(GameThread.java:81)
[2021-12-03T23:59:01.0345905] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-12-03T23:59:01.0345905] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-12-03T23:59:01.0345905] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
[2021-12-03T23:59:01.0345905] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
[2021-12-03T23:59:01.0355919] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
[2021-12-03T23:59:01.0355919] 	... 6 more
[2021-12-03T23:59:01.0355919] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-12-03T23:59:01.0355919] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-03T23:59:01.0355919] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-03T23:59:01.0355919] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-03T23:59:01.0355919] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-12-03T23:59:01.0355919] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-12-03T23:59:01.0365896] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-12-03T23:59:01.0365896] 	... 12 more
[2021-12-03T23:59:01.0365896] Caused by: java.net.ConnectException: Connection timed out: connect
[2021-12-03T23:59:01.0375892] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-12-03T23:59:01.037658] 	at java.base/sun.nio.ch.Net.connect(Net.java:503)
[2021-12-03T23:59:01.037658] 	at java.base/sun.nio.ch.Net.connect(Net.java:492)
[2021-12-03T23:59:01.037658] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-12-03T23:59:01.037658] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-12-03T23:59:01.037658] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-12-03T23:59:01.037658] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-12-03T23:59:01.037658] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-12-03T23:59:01.037658] 	... 15 more
